### ISSUE TITLE
App crashes if survey is not completed first before navigating to Today's weather

### ISSUE THREAD

**Issue by iAmTheDolphin** [packing-list/495-Packing-List#7]
Instructions to replicate, 
1) open AVD Manager
2) right click your device
3) select "Wipe Data"
4) re run the app
5) open "Today's Weather" before completing the survey

--------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.packinglist, PID: 4726
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.packinglist/com.example.packinglist.TodaysWeatherActivity}: java.util.NoSuchElementException: Key FootwearCold is missing in the map.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at 

android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.util.NoSuchElementException: Key FootwearCold is missing in the map.
        at 

kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
        at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:294)
        at com.example.packinglist.WeatherData$clothing$2.invoke(WeatherData.kt:21)
        at com.example.packinglist.WeatherData$clothing$2.invoke(WeatherData.kt:3)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.example.packinglist.WeatherData.getClothing(Unknown Source:7)
        at com.example.packinglist.TodaysWeatherActivity.onCreate(TodaysWeatherActivity.kt:42)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at

 android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
I/Process: Sending signal. PID: 4726 SIG: 9

**Comment by andrasveto** [comment]
This isn't really a bug. The ui for the app is just for testing right now. Once it's actually complete, you're going to be forced to take the survey prior to being able to do anything else.

**Comment by iAmTheDolphin** [comment]
yeah but in the app's current form it is a bug. Shouldn't we leave it open to confirm it's fixed and we don't leave it in there

**Comment by andrasveto** [comment]
fair enough

**Comment by andrasveto** [comment]
Fixed in https://github.com/packing-list/495-Packing-List/pull/8
